//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 刷刷刷 {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class soce {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal soce() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("刷刷刷.soce", typeof(soce).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 don&apos;t 的本地化字符串。
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Buy64 {
            get {
                object obj = ResourceManager.GetObject("Buy64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon favicon_20190501082203512 {
            get {
                object obj = ResourceManager.GetObject("favicon_20190501082203512", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 王者荣耀 的本地化字符串。
        /// </summary>
        public static string g1 {
            get {
                return ResourceManager.GetString("g1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 荒野行动 的本地化字符串。
        /// </summary>
        public static string g10 {
            get {
                return ResourceManager.GetString("g10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 皇室战争 的本地化字符串。
        /// </summary>
        public static string g11 {
            get {
                return ResourceManager.GetString("g11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部落冲突 的本地化字符串。
        /// </summary>
        public static string g12 {
            get {
                return ResourceManager.GetString("g12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string g13 {
            get {
                return ResourceManager.GetString("g13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string g14 {
            get {
                return ResourceManager.GetString("g14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string g15 {
            get {
                return ResourceManager.GetString("g15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string g16 {
            get {
                return ResourceManager.GetString("g16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string g17 {
            get {
                return ResourceManager.GetString("g17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string g18 {
            get {
                return ResourceManager.GetString("g18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string g19 {
            get {
                return ResourceManager.GetString("g19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 穿越火线：枪战王者 的本地化字符串。
        /// </summary>
        public static string g2 {
            get {
                return ResourceManager.GetString("g2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string g20 {
            get {
                return ResourceManager.GetString("g20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string g21 {
            get {
                return ResourceManager.GetString("g21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string g22 {
            get {
                return ResourceManager.GetString("g22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string g23 {
            get {
                return ResourceManager.GetString("g23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string g24 {
            get {
                return ResourceManager.GetString("g24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string g25 {
            get {
                return ResourceManager.GetString("g25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string g26 {
            get {
                return ResourceManager.GetString("g26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string g27 {
            get {
                return ResourceManager.GetString("g27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string g28 {
            get {
                return ResourceManager.GetString("g28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string g29 {
            get {
                return ResourceManager.GetString("g29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完美世界 的本地化字符串。
        /// </summary>
        public static string g3 {
            get {
                return ResourceManager.GetString("g3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string g30 {
            get {
                return ResourceManager.GetString("g30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string g31 {
            get {
                return ResourceManager.GetString("g31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 明日之后 的本地化字符串。
        /// </summary>
        public static string g4 {
            get {
                return ResourceManager.GetString("g4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 穿越火线 的本地化字符串。
        /// </summary>
        public static string g5 {
            get {
                return ResourceManager.GetString("g5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英雄联盟 的本地化字符串。
        /// </summary>
        public static string g6 {
            get {
                return ResourceManager.GetString("g6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第五人格 的本地化字符串。
        /// </summary>
        public static string g7 {
            get {
                return ResourceManager.GetString("g7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绝地求生：刺激战场 的本地化字符串。
        /// </summary>
        public static string g8 {
            get {
                return ResourceManager.GetString("g8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绝地求生：全军出击 的本地化字符串。
        /// </summary>
        public static string g9 {
            get {
                return ResourceManager.GetString("g9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap 刷刷刷Icon {
            get {
                object obj = ResourceManager.GetObject("刷刷刷Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap 刷刷刷启动画面 {
            get {
                object obj = ResourceManager.GetObject("刷刷刷启动画面", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
